{% set version = "12.2.0" %}
{% set python_min = "3.11.0" %}
package:
  name: testfixtures
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/testfixtures/testfixtures-{{ version }}.tar.gz
  sha256: 3d20c1834b1308ce2ecbd3d7eafe3c970315163df0f1f491dbf66a6150af6c85

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - testfixtures

about:
  home: https://testfixtures.readthedocs.io
  license: MIT
  license_file: LICENSE.txt
  summary: A collection of helpers and mock objects for unit tests and doc tests.
  doc_url: https://testfixtures.readthedocs.io
  dev_url: https://github.com/Simplistix/testfixtures

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - cjw296
